instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instagram/posts/urls.py
from django.urls import path

from .views import (
    index, lenta_of_posts,
    post_create, DetailPostView,
    post_like, DeletePostView,
    UpdatePostView
)


app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('lenta/', lenta_of_posts, name='lenta'),
    path('<int:post_pk>/', DetailPostView.as_view(), name='post-detail'),
    path('post-create/', post_create, name='post-create'),
    path('post-update/<int:post_pk>/', UpdatePostView.as_view(), name='post-update'),
    path('post-delete/<int:post_pk>/', DeletePostView.as_view(), name='post-delete'),
    path('like/<int:post_pk>/', post_like, name='like'),
]

instagram/users/urls.py
from django.urls import path

from .views import (
    CustomLoginView, CustomLogoutView, SignupView,
    ProfileView, ProfileEditView, AddFriendView
)


app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/',
         AddFriendView.as_view(),
         name='add_remove_friend'
         )
]

instagram/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import now


User = get_user_model()


class HashTag(models.Model):
    name = models.CharField('Название', max_length=20, unique=True)

    class Meta:
        verbose_name = 'Хештег'
        verbose_name_plural = 'Хештеги'
        ordering = ('name', )

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    hashtags = models.ManyToManyField(HashTag, related_name='posts', blank=True)
    name = models.CharField(
        'заголовок',
        max_length=80,
        blank=True
    )
    image = models.ImageField('картинка', upload_to='posts')
    description = models.TextField(
        'описание',
        max_length=1000,
        blank=True
    )
    pub_date = models.DateTimeField('дата публикации', auto_now_add=True)
    edit_date = models.DateTimeField('дата редактирования', auto_now=True)
    timezone = models.CharField('часовой пояс', default='Europe/Samara', max_length=50)
    location = models.CharField('место съёмки', default='Тольятти', max_length=50)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return f"Пост {self.pk} от {self.author}"

    @property
    def count_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    text = models.TextField('текст комментария', max_length=250)
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    pub_date = models.DateTimeField('дата публикации', default=now)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-pub_date', 'text')

    def __str__(self):
        return f"Комментарий {self.pk} от {self.author}"

instagram/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.Form):
    name = forms.CharField(
        label="Название",
        max_length=80,
        required=True,
    )

    image = forms.ImageField(label="Картинка", required=True)
    description = forms.CharField(label="Описание", max_length=1000)


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'image', 'description']

    def clean_name(self):
        name = self.cleaned_data.get('name', None)
        if name:
            if len(name) < 4 or len(name) > 50:
                raise ValidationError('Название должно быть нормальной длины (от 4 до 50)')
            if not name[0].isupper:
                raise ValidationError('Название должно начинаться с заглавной буквы')
            return name
        else:
            raise ValidationError('Название обязательно!')

    def clean_image(self):
        image = self.cleaned_data.get('image', None)
        if image:
            if image.size > 5242880:
                raise ValidationError('Слишком большой размер')
            return image
        else:
            raise ValidationError('Картинка обязательна!')

instagram/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, UpdateView, DetailView

from .forms import PostForm, PostModelForm
from .models import Post


def index(request):
    posts = Post.objects.all().annotate(
        likes_count=Count('likes')
    ).order_by(
        '-likes_count'
    )[:10]
    output = render_to_string('posts/index.html', {'posts': posts}, request=request)
    return HttpResponse(output)


def lenta_of_posts(request):
    user = request.user
    if user.is_authenticated:
        friends = user.friends.all()
        posts = Post.objects.filter(author__target_friends__in=friends).annotate(
            likes_count=Count('likes')
        )
        return render(request, 'posts/lenta_of_posts.html', {'posts': posts})
    else:
        raise PermissionDenied("Пожалуйста авторизируйтесь")


class DetailPostView(DetailView):
    model = Post
    pk_url_kwarg = 'post_pk'
    template_name = 'posts/post_detail.html'


@login_required
def post_create(request):

    if request.method == 'GET':
        form = PostModelForm()
    else:
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:index')

    return render(request, 'posts/post_create.html', {
        'form': form, 'header': "Создание поста",
    })


@method_decorator(login_required, name='dispatch')
class UpdatePostView(UpdateView):
    model = Post
    pk_url_kwarg = 'post_pk'
    template_name = 'posts/post_update.html'
    form_class = PostModelForm

    def get_success_url(self):
        object = self.get_object()
        return reverse('posts:post-detail', kwargs={'post_pk': object.pk})

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if self.request.user == object.author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied("Вы не автор! Вам нельзя! :0")


@method_decorator(login_required, name='dispatch')
class DeletePostView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_pk'
    template_name = 'posts/post_delete.html'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if self.request.user == object.author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied("Вы не автор! Вам нельзя! :0")

    def get_success_url(self):
        return reverse('posts:index')


@login_required
def post_like(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return redirect(request.META.get('HTTP_REFERER'), request)

instagram/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Лента новостей
{% endblock title %}

{% block content %}
<ul>
{% if not request.user.is_authenticated %}
    <form action="login/" target="_blank">
        {% csrf_token %}
        <button type="submit">Вход/Регистрация</button>
{% endif %}
    <h1>Лучшие посты:</h1>
    {% for post in posts %}
    <li>
        <h2>
            <a href="{% url 'posts:post-detail' post_pk=post.pk %}">
                {{post.name}}
            </a>
        </h2>
        {% if request.user.is_authenticated and request.user == post.author %}
            <a href="{% url 'posts:post-update' post.pk %}">✍️</a>
            <a href="{% url 'posts:post-delete' post.pk %}">❌</a>
        {% endif %}
            <a href="{% url 'users:profile' post.author.id %}">{{post.author}}</a>
        {{ post.date_creation|date:"d.m.Y H:i" }}
        <p>{{post.description}}</p>
        {% if request.user.is_authenticated and request.user in post.likes.all %}
            <a href="{% url 'posts:like' post.pk %}">❤️ {{post.count_of_likes}}</a>
        {% elif request.user.is_authenticated %}
            <a href="{% url 'posts:like' post.pk %}">♡ {{post.count_of_likes}}</a>
        {% else %}
        <a>❤️ {{post.count_of_likes}}</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endblock content %}

instagram/posts/templates/posts/lenta_of_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <a href="{% url 'posts:index' %}">Главная</a>
    <title>Посты друзей</title>
</head>
<body>
    <ul>
        <h1>Посты друзей:</h1>
        {% if posts %}
            {% for post in posts %}
            <li>
                <h2>
                    <a href="{% url 'posts:post-detail' post_pk=post.pk %}">
                        {{post.name}}
                    </a>
                </h2>
                <p>{{post.author}}</p>
                <p>{{post.description}}</p>
                <p>Лайки: {{post.count_of_likes}}</p>
                {% if request.user in post.likes.all %}
                    <a href="{% url 'posts:like' post.pk %}">❤️</a>
                {% else %}
                    <a href="{% url 'posts:like' post.pk %}">♡</a>
                {% endif %}
            </li>
        {% endfor %}
        {% else %}
            <h2>Посты друзей не найдены... 🙈</h2>
        {% endif %}
    </ul>
</body>
</html>

instagram/posts/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
    {{ header }}
{% endblock title %}

{% block content %}
    <h1>{{ header }}</h1>
    <form action="{% url 'posts:post-create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock content %}

instagram/posts/templates/posts/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Удаление поста</title>
</head>
<body>
    <form action="{% url 'posts:post-delete' post.pk %}" method="post">
        {% csrf_token %}
        <button type="submit">Подтверждение удаления</button>
    </form>
</body>
</html>

instagram/posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <a href="{% url 'posts:index' %}">Главная</a>
    <title>{{post.name}}</title>
</head>
<body>
    <h1>{{post.name}}</h1>
    {% if request.user.is_authenticated and request.user == post.author %}
        <a href="{% url 'posts:post-update' post.pk %}">✍️</a>
        <a href="{% url 'posts:post-delete' post.pk %}">❌</a>
    {% endif %}
    <p>{{post.author}}</p>
    {{ post.date_creation|date:"d.m.Y H:i" }}
    <p>{{post.description}}</p>
    {% if request.user.is_authenticated and request.user in post.likes.all %}
        <a href="{% url 'posts:like' post.pk %}">❤️ {{post.count_of_likes}}</a>
    {% elif request.user.is_authenticated %}
        <a href="{% url 'posts:like' post.pk %}">♡ {{post.count_of_likes}}</a>
    {% else %}
        <a>❤️ {{post.count_of_likes}}</a>
    {% endif %}
    <img src="{{ post.image.url }}" alt="{{post.name}}">
</body>
</html>

instagram/posts/templates/posts/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновить пост</title>
</head>
<body>
    <h1>Обновление поста</h1>
    <form action="{% url 'posts:post-update' post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update!</button>
    </form>
</body>
</html>