instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instagram/posts/urls.py
from django.urls import path

from .views import (
    index, lenta_of_posts,
    post_create, DetailPostView,
    post_like, DeletePostView,
    UpdatePostView
)


app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('lenta/', lenta_of_posts, name='lenta'),
    path('<int:post_pk>/', DetailPostView.as_view(), name='post-detail'),
    path('post-create/', post_create, name='post-create'),
    path('post-update/<int:post_pk>/', UpdatePostView.as_view(), name='post-update'),
    path('post-delete/<int:post_pk>/', DeletePostView.as_view(), name='post-delete'),
    path('like/<int:post_pk>/', post_like, name='like'),
]

instagram/users/urls.py
from django.urls import path

from .views import (
    CustomLoginView, CustomLogoutView, SignupView,
    ProfileView, ProfileEditView, AddFriendView
)


app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/',
         AddFriendView.as_view(),
         name='add_remove_friend'
         )
]

instagram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Q, F


class CustomUser(AbstractUser):
    birth_date = models.DateField('дата рождения', blank=True, null=True)
    about = models.TextField(max_length=1000, blank=True)
    avatar = models.ImageField(upload_to='users')
    phone_number = models.CharField(max_length=11, blank=True)
    my_friends = models.ManyToManyField('self', through='Friendship', blank=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f"User {self.username}"


class Friendship(models.Model):
    source = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='friends'
    )

    target = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='target_friends'
    )
    is_accepted = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Друг'
        verbose_name_plural = 'Друзья'
        constraints = [
            models.UniqueConstraint(
                fields=['source', 'target'],
                name='unique_source_target'
            ),
            models.CheckConstraint(
                check=~Q(source=F('target')),
                name='source_not_target'
            )
        ]

instagram/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm

from .models import CustomUser


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        "autofocus": True,
        "placeholder": "Имя пользователя",
        "class": "form-control",
    }))
    password = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            "class": "form-control",
        }),
    )


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "avatar", "about")


class UserEditForm(forms.ModelForm):
    birth_date = forms.DateField(
        label="Дата рождения",
        widget=forms.DateInput(
            attrs={
                'type': 'date',
            }
        )
    )

    class Meta:
        model = CustomUser
        fields = (
            'first_name', 'last_name',
            'email', 'phone_number',
            'birth_date', 'about',
            'avatar'
        )

instagram/users/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, UpdateView

from .forms import LoginForm, SignupForm, UserEditForm
from .models import CustomUser


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    next_page = reverse_lazy('posts:index')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('users:login')
    http_method_names = ['post', ]


class SignupView(View):
    template_name = 'users/signup.html'
    form = SignupForm

    def get_context_data(self):
        context = {
            'form': self.form
        }

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, request.FILES)
        context = self.get_context_data()
        context['form'] = form

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('posts:index'))
        else:
            return render(request, self.template_name, context)


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        object = self.get_object()
        context = super().get_context_data(**kwargs)
        context['header'] = f"{object.username}"
        return context


@method_decorator(login_required, name='dispatch')
class ProfileEditView(UpdateView):
    model = CustomUser
    template_name = 'users/edit_profile.html'
    form_class = UserEditForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        object = self.get_object()
        return reverse('users:profile', kwargs={'user_id': object.id})


@method_decorator(login_required, name='dispatch')
class AddFriendView(View):
    http_method_names = ['post',]

    def post(self, request, user_id, *args, **kwargs):
        friend = get_object_or_404(CustomUser, id=user_id)
        me = request.user

        if me.my_friends.filter(id=friend.id).exists():
            me.my_friends.remove(friend)
        else:
            me.my_friends.add(friend)
        return redirect(request.META.get('HTTP_REFERER'), request)

instagram/users/templates/users/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактирование профиля</title>
</head>
<body>
    <h1>Редактирование профиля</h1>
    <form action="{% url 'users:edit_profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Обновить</button>
    </form>
</body>
</html>

instagram/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <a href="{% url 'posts:index' %}">Главная</a>
    <title>Страничка входа</title>
</head>
    <body>
    <h1>Страничка входа</h1>
    <form action="{% url 'users:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
    <form action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        <button type="submit">Регистрация</button>
    </form>
    </body>
</html>

instagram/users/templates/users/profile.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{header}}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'users/css/profile.css' %}">
    <a href="{% url 'posts:index' %}">Главная</a>
</head>
<body>
    <h1>{{header}}</h1>
    {% if user.id == profile.id %}
        <a href="{% url 'users:edit_profile' %}">Редактировать профиль</a>
    {% elif request.user.is_authenticated %}
        <form action="{% url 'users:add_remove_friend' profile.id  %}" method="post">
            {% csrf_token %}
            {% if profile in user.my_friends.all %}
             <button type="submit">Удалить из друзей</button>
            {% else %}
            <button type="submit">Добавить в друзья</button>
            {% endif %}
        </form>
    {% endif %}

    <h2>Информация:</h2>
    {% if profile.avatar %}
        <img class="avatar" src="{{profile.avatar.url}}" alt="avatar">
    {% else %}
        <img class="avatar" src="{% static 'users/images/avatar.jpg' %}" alt="avatar">
    {% endif %}
    <p>Имя аккаунта: {{ profile.username }}</p>
    <p>Имя: {{ profile.first_name }}</p>
    <p>Фамилия: {{ profile.last_name }}</p>
    <p>Дата рождения: {{ profile.birth_date|date:"d M Y" }}</p>
    <p>О Вас: {{ profile.about|linebreaks }}</p>
    <p>Email: {{ profile.email }}</p>
    <p>Номер телефона: {{ profile.phone_number }}</p>
</body>
</html>

instagram/users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <a href="{% url 'posts:index' %}">Главная</a>
    <title>Страничка регистрации</title>
</head>
<body>
    <h1>Страничка регистрации</h1>
    <form action="{% url 'users:signup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>