instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instagram/posts/urls.py
from django.urls import path

from .views import (
    index, lenta_of_posts,
    post_create, DetailPostView,
    post_like, DeletePostView,
    UpdatePostView
)


app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('lenta/', lenta_of_posts, name='lenta'),
    path('<int:post_pk>/', DetailPostView.as_view(), name='post-detail'),
    path('post-create/', post_create, name='post-create'),
    path('post-update/<int:post_pk>/', UpdatePostView.as_view(), name='post-update'),
    path('post-delete/<int:post_pk>/', DeletePostView.as_view(), name='post-delete'),
    path('like/<int:post_pk>/', post_like, name='like'),
]

instagram/users/urls.py
from django.urls import path

from .views import (
    CustomLoginView, CustomLogoutView, SignupView,
    ProfileView, ProfileEditView, AddFriendView
)


app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/',
         AddFriendView.as_view(),
         name='add_remove_friend'
         )
]

instagram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Базовый шаблон
        {% endblock title %}
    </title>
</head>
<body>
    {% include 'header.html' %}
    {% include 'menu.html' %}

    {% block content %}
        <h1>Пусто</h1>
    {% endblock content %}

    {% include 'footer.html' %}
</body>
</html>

instagram/templates/footer.html
<footer>
Связь с нами:
    Email: jinx163@mail.ru
</footer>

instagram/templates/header.html
<header>
   ...заголовок...
</header>

instagram/templates/menu.html
{% if user.is_authenticated %}
    <a href="{% url 'posts:post-create' %}">Создать пост</a>
    <a href="{% url 'users:profile' user.id %}">Мой профиль</a>
    <a href="{% url 'posts:lenta' %}">Посты друзей</a>
    <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Выйти</button>
    </form>
{% endif %}